spring.application.name=ExternalConfigServer
server.port=9894

#link to git (Git location where properties file exist)
spring.cloud.config.server.git.uri=https://github.com/kamleshstech/config-app-props

