spring.application.name=MultipleDB

#H2
spring.datasource.d1.url=jdbc:h2:mem:testdb
spring.datasource.d1.username=sa
spring.datasource.d1.password=sa
spring.datasource.d1.driver-class-name=org.h2.Driver

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

#mysql
spring.datasource.d2.url=jdbc:mysql://localhost:3306/boot
spring.datasource.d2.username=root
spring.datasource.d2.password=root
spring.datasource.d2.driver-class-name=com.mysql.cj.jdbc.Driver


spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=create-drop