spring.application.name=Native-Config-Server
server.port=9894
#enable native config, default is external
spring.profiles.active=native
spring.cloud.config.server.native.search-locations=classpath:/myconf/
