spring.application.name=ConsumerApp-JMS-ActiveMQ
server.port=8084

#link to active MQ(MOM)
spring.activemq.broker-url=tcp://localhost:61616
spring.activemq.user=admin
spring.activemq.password=admin

#peer to peer communication enable if below property is false 
spring.jms.pub-sub-domain=true
